---
language: ruby
sudo: required
cache: bundler
bundler_args: --without local_development
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install aspell
  - sudo apt-get install aspell-es
  - gem install bundler
script:
  - bundle exec rake spec
  - bundle exec rake lint:style
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - rbx-2
  - ruby-head
matrix:
  include:
    - rvm: jruby
      env: JRUBY_OPTS='--2.0 --server -Xcompile.invokedynamic=false'
    - rvm: jruby-head
      env: JRUBY_OPTS='--server -Xcompile.invokedynamic=false'
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby
    - rvm: jruby-head
    - rvm: ruby-head
addons:
  code_climate:
    repo_token: 39bba5a92bbd8942dbe7a7a49757088cb639e800268b77b709904135a64e5a5f
...
