---
# RuboCop tool configuration used by rake lint:style command.
AllCops:
  DisplayCopNames: true
  Exclude:
    - '**/mdspell.gemspec'
    - 'vendor/**/*'

Metrics/LineLength:
  Max: 99

Metrics/MethodLength:
  Max: 20
...
